export enum MODALS {
  LOGIN_MODAL = 'LOGIN_MODAL',
  REGISTER_MODAL = 'REGISTER_MODAL',
  DELETE_MODAL = 'DELETE_MODAL',
  EDIT_PROFILE_MODAL = 'EDIT_PROFILE_MODAL',
  AUTH_FOLLOWER_MODAL = 'AUTH_FOLLOWER_MODAL',
  USER_FOLLOWER_MODAL = 'USER_FOLLOWER_MODAL',
  PASSWORD_AUTH_MODAL = 'PASSWORD_AUTH_MODAL',
  DISCUSSION_MODAL = 'DISCUSSION_MODAL',
  LIKE_MODAL = 'LIKE_MODAL',
  USER_SUGGESTION_MODAL = 'USER_SUGGESTION_MODAL',
  CHANGE_PASSWORD_MODAL = 'CHANGE_PASSWORD_MODAL',
  DELETE_ACCOUNT_MODAL = 'DELETE_ACCOUNT_MODAL',
  COMPLETE_PROFILE_MODAL = 'COMPLETE_PROFILE_MODAL',
}

export enum SORT_TYPE {
  LIKE_COUNT = 'likedBy',
  CREATED_AT = 'createdAt',
}

export enum SORT_ORDER {
  ASC = 'asc',
  DESC = 'desc',
}

export const NOTIFICATIONS_TYPE = Object.freeze({
  FOLLOW_USER: 'FOLLOW_USER',
  LIKE_BLOG: 'LIKE_BLOG',
  LIKE_COMMENT: 'LIKE_COMMENT',
  POST_COMMENT: 'POST_COMMENT',
  POST_BLOG: 'POST_BLOG',
});

export const NOTIFICATIONS_STATUS = Object.freeze({
  READ: 'READ',
  UNREAD: 'UNREAD',
});

export enum FILTERS {
  HOME_BLOG_FILTER = 'HOME_BLOG_FILTER',
  FOLLOWING_BLOG_FILTER = 'FOLLOWING_BLOG_FILTER',
  USER_SUGGESTION_FILTER = 'USER_SUGGESTION_FILTER',
  GENERIC_BLOG_FILTER = 'GENERIC_BLOG_FILTER',
  BOOKMARK_FILTER = 'BOOKMARK_FILTER',
  NOTIFICATION_FILTER = 'NOTIFICATION_FILTER',
  LIKE_FILTER = 'LIKE_FILTER',
  COMMENT_FILTER = 'COMMENT_FILTER',
  AUTH_PROFILE_FILTER = 'AUTH_PROFILE_FILTER',
  USER_PROFILE_FILTER = 'USER_PROFILE_FILTER',
  AUTH_FOLLOWER_FILTER = 'AUTH_FOLLOWER_FILTER',
  AUTH_FOLLOWING_FILTER = 'AUTH_FOLLOWING_FILTER',
  USER_FOLLOWER_FILTER = 'USER_FOLLOWER_FILTER',
  USER_FOLLOWING_FILTER = 'USER_FOLLOWING_FILTER',
}
