export enum NOTIFICATION_STATUS {
  READ = 'READ',
  UNREAD = 'UNREAD',
}

export enum NOTIFICATION_TYPE {
  FOLLOW_USER = 'FOLLOW_USER',
  POST_BLOG = 'POST_BLOG',
  LIKE_BLOG = 'LIKE_BLOG',
  POST_COMMENT = 'POST_COMMENT',
  LIKE_COMMENT = 'LIKE_COMMENT',
}
